<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('messages', function (Blueprint $table) {
            // agent = generated by the AI | impersonated = written by the user as an agent | note = director note
            $table->string('type', 20)->default('agent')->after('agent_id');
            // For notes: which chat_agent this note is addressed to (NULL = all participants)
            $table->unsignedBigInteger('target_chat_agent_id')->nullable()->after('type');
            $table->foreign('target_chat_agent_id')->references('id')->on('chat_agents')->cascadeOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('messages', function (Blueprint $table) {
            $table->dropForeign(['target_chat_agent_id']);
            $table->dropColumn(['type', 'target_chat_agent_id']);
        });
    }
};
